In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving datasetFinal.csv to datasetFinal.csv


In [ ]:
df = pd.read_csv('datasetFinal.csv')

In [ ]:
df.dropna(inplace=True)

In [ ]:
X = df.iloc[:, 3:].values
y = df.iloc[:, 2].values

In [ ]:
X


array([[1., 2., 1., ..., 1., 2., 1.],
       [0., 0., 0., ..., 2., 6., 1.],
       [0., 0., 0., ..., 0., 1., 2.],
       ...,
       [0., 0., 0., ..., 1., 3., 1.],
       [2., 3., 5., ..., 0., 2., 2.],
       [0., 0., 0., ..., 1., 4., 1.]])

In [ ]:
y

array([ True,  True,  True, ...,  True,  True,  True])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
from collections import Counter
Counter(y_test)

Counter({False: 245, True: 518})

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)



GaussianNB()

In [ ]:
y_pred = nb.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[ 25 220]
 [ 31 487]]
              precision    recall  f1-score   support

       False       0.45      0.10      0.17       245
        True       0.69      0.94      0.80       518

    accuracy                           0.67       763
   macro avg       0.57      0.52      0.48       763
weighted avg       0.61      0.67      0.59       763

