In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.read_csv("C:\\Users\\Administrator\\Downloads\\datasetFinal.csv")

In [ ]:
df.dropna(inplace=True)

In [ ]:
X = df.iloc[:, 3:].values
y = df.iloc[:, 2].values

In [ ]:
X


array([[1., 2., 1., ..., 1., 2., 1.],
       [0., 0., 0., ..., 2., 6., 1.],
       [0., 0., 0., ..., 0., 1., 2.],
       ...,
       [0., 0., 0., ..., 1., 3., 1.],
       [2., 3., 5., ..., 0., 2., 2.],
       [0., 0., 0., ..., 1., 4., 1.]])

In [ ]:
y

array([ True,  True,  True, ...,  True,  True,  True])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
from collections import Counter
Counter(y_test)

Counter({True: 515, False: 248})

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF= RandomForestClassifier(n_estimators=20 , random_state = 0)
RF.fit(X_train , y_train)



RandomForestClassifier(n_estimators=20, random_state=0)

In [ ]:
y_pred = RF.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[148 100]
 [111 404]]
              precision    recall  f1-score   support

       False       0.57      0.60      0.58       248
        True       0.80      0.78      0.79       515

    accuracy                           0.72       763
   macro avg       0.69      0.69      0.69       763
weighted avg       0.73      0.72      0.72       763

